workflows:
  android-workflow:
    name: VoiceCallPro Android
    max_build_duration: 30
    environment:
      java: 17
    scripts:
      - name: Download gradle wrapper jar
        script: |
          mkdir -p gradle/wrapper
          curl -Lo gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v8.4.0/gradle/wrapper/gradle-wrapper.jar
      - name: Set gradlew executable
        script: chmod +x gradlew
      - name: Build debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
